"""Planner - LLM-powered task decomposition for natural language goals.

Takes a user's natural language goal and decomposes it into
a structured plan of Tool Layer actions.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel


class TaskStep(BaseModel):
    """A single step in an execution plan."""
    id: int
    tool: str  # Tool Layer function to call
    description: str  # Human-readable description
    args: dict[str, Any] = {}
    depends_on: list[int] = []  # Step IDs this depends on


class ExecutionPlan(BaseModel):
    """A structured plan generated by the Planner."""
    goal: str
    target: str
    device: str = "local"
    steps: list[TaskStep] = []
    estimated_rounds: int = 1


# System prompt for the LLM planner
PLANNER_SYSTEM_PROMPT = """\
You are FridaPilot's task planner. Given a user's natural language goal about \
dynamic analysis with Frida, decompose it into concrete steps using available tools.

Available tools:
- recon.list_processes(device) -> List running processes
- recon.enumerate_modules(session) -> List loaded modules
- recon.enumerate_classes(session, filter_prefix) -> List Java/ObjC classes
- recon.enumerate_methods(session, class_name) -> List methods of a class
- recon.enumerate_exports(session, module_name) -> List module exports
- injector.attach(target, device) -> Attach to process
- injector.spawn(package, device) -> Spawn and attach
- injector.inject(session, script) -> Inject Frida script
- injector.detach(session) -> Detach
- script_forge.get_template(name, **kwargs) -> Load script template
- observer.collect(session, timeout) -> Collect messages
- bypass.get_ssl_bypass_script() -> SSL pinning bypass script
- bypass.get_anti_debug_script() -> Anti-debug bypass script
- crypto_reverse.scan_binary(path) -> Scan binary for crypto
- crypto_reverse.get_bcrypt_hook_script() -> BCrypt hook script

Output a JSON plan with steps. Each step has: id, tool, description, args, depends_on.

Example:
{
  "goal": "Monitor HTTPS traffic of Android app",
  "target": "com.example.app",
  "device": "usb",
  "steps": [
    {"id": 1, "tool": "injector.spawn", "description": "Spawn target app", "args": {"package": "com.example.app", "device": "usb"}, "depends_on": []},
    {"id": 2, "tool": "bypass.get_ssl_bypass_script", "description": "Get SSL bypass script", "args": {}, "depends_on": []},
    {"id": 3, "tool": "injector.inject", "description": "Inject SSL bypass", "args": {"script": "$step2.result"}, "depends_on": [1, 2]},
    {"id": 4, "tool": "observer.collect", "description": "Collect network data", "args": {"timeout": 30}, "depends_on": [3]}
  ]
}
"""


async def create_plan(
    goal: str,
    target: str = "",
    device: str = "local",
    llm_client: Any = None,
) -> ExecutionPlan:
    """Use LLM to create an execution plan from a natural language goal.

    Args:
        goal: Natural language description of the task.
        target: Target process/package name.
        device: Device type (local/usb/remote).
        llm_client: LiteLLM-compatible client. If None, uses default.

    Returns:
        An ExecutionPlan with concrete steps.
    """
    if llm_client is None:
        from litellm import acompletion
        response = await acompletion(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
                {"role": "user", "content": f"Goal: {goal}\nTarget: {target}\nDevice: {device}"},
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
        )
        plan_json = json.loads(response.choices[0].message.content)
    else:
        # Custom LLM client support
        plan_json = await llm_client.plan(goal, target, device)

    return ExecutionPlan(**plan_json)
