"""Reporter - Generate Markdown/JSON reports from execution results."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

from fridapilot.agent.executor import StepResult, ExecutionContext
from fridapilot.agent.planner import ExecutionPlan


def generate_report(
    plan: ExecutionPlan,
    results: list[StepResult],
    ctx: ExecutionContext,
    format: str = "md",
) -> str:
    """Generate a report from plan execution results.

    Args:
        plan: The execution plan.
        results: Step results.
        ctx: Execution context with collected messages.
        format: "md" for Markdown, "json" for JSON.

    Returns:
        Report content as string.
    """
    if format == "json":
        return _json_report(plan, results, ctx)
    return _markdown_report(plan, results, ctx)


def _markdown_report(
    plan: ExecutionPlan,
    results: list[StepResult],
    ctx: ExecutionContext,
) -> str:
    """Generate a Markdown report."""
    lines = [
        "# FridaPilot Execution Report\n",
        f"**Goal:** {plan.goal}",
        f"**Target:** {plan.target}",
        f"**Device:** {plan.device}",
        f"**Time:** {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Execution Summary\n",
        f"- Total steps: {len(results)}",
        f"- Succeeded: {sum(1 for r in results if r.success)}",
        f"- Failed: {sum(1 for r in results if not r.success)}",
        f"- Total duration: {sum(r.duration for r in results):.2f}s",
        "",
        "## Steps\n",
    ]

    for r in results:
        status = "OK" if r.success else "FAIL"
        lines.append(f"### Step {r.step_id}: {r.tool} [{status}]")
        lines.append(f"Duration: {r.duration:.2f}s\n")
        if r.success:
            result_str = _safe_str(r.result, max_len=500)
            lines.append(f"```\n{result_str}\n```\n")
        else:
            lines.append(f"**Error:** {r.error}\n")

    if ctx.messages:
        lines.append("## Collected Messages\n")
        lines.append(f"Total: {len(ctx.messages)}\n")
        for msg in ctx.messages[:50]:
            lines.append(f"- `{_safe_str(msg, max_len=200)}`")
        if len(ctx.messages) > 50:
            lines.append(f"\n... and {len(ctx.messages) - 50} more messages")

    # Sensitive data findings (from Observer)
    sensitive = _collect_sensitive(ctx)
    if sensitive:
        lines.append("\n## Sensitive Data Detected\n")
        lines.append(f"**Total findings: {len(sensitive)}**\n")
        high = [s for s in sensitive if s.get("severity") == "HIGH"]
        medium = [s for s in sensitive if s.get("severity") == "MEDIUM"]
        if high:
            lines.append(f"### HIGH Severity ({len(high)})\n")
            for s in high:
                lines.append(f"- **{s['pattern']}**: `{s['preview']}` (message #{s['index']})")
        if medium:
            lines.append(f"\n### MEDIUM Severity ({len(medium)})\n")
            for s in medium:
                lines.append(f"- **{s['pattern']}**: `{s['preview']}` (message #{s['index']})")

    lines.append("\n---\n*Generated by FridaPilot*")
    return "\n".join(lines)


def _json_report(
    plan: ExecutionPlan,
    results: list[StepResult],
    ctx: ExecutionContext,
) -> str:
    """Generate a JSON report."""
    report = {
        "goal": plan.goal,
        "target": plan.target,
        "device": plan.device,
        "timestamp": time.strftime('%Y-%m-%dT%H:%M:%S'),
        "summary": {
            "total_steps": len(results),
            "succeeded": sum(1 for r in results if r.success),
            "failed": sum(1 for r in results if not r.success),
            "total_duration": sum(r.duration for r in results),
        },
        "steps": [
            {
                "id": r.step_id,
                "tool": r.tool,
                "success": r.success,
                "duration": r.duration,
                "result": _safe_str(r.result, max_len=1000) if r.success else None,
                "error": r.error if not r.success else None,
            }
            for r in results
        ],
        "messages": ctx.messages[:100],
        "sensitive_data": _collect_sensitive(ctx),
    }
    return json.dumps(report, indent=2, default=str)


def _collect_sensitive(ctx: ExecutionContext) -> list[dict]:
    """Extract sensitive data findings from the execution context's session observer."""
    findings: list[dict] = []
    if ctx.session is not None and hasattr(ctx.session, "observer"):
        observer = ctx.session.observer
        if hasattr(observer, "sensitive_findings"):
            for s in observer.sensitive_findings:
                findings.append({
                    "pattern": s.pattern_name,
                    "preview": s.value_preview,
                    "index": s.message_index,
                    "severity": s.severity,
                })
    return findings


def save_report(content: str, output_path: str) -> None:
    """Write report content to a file."""
    Path(output_path).write_text(content, encoding="utf-8")


def _safe_str(obj: Any, max_len: int = 200) -> str:
    """Safely convert any object to a truncated string."""
    try:
        s = json.dumps(obj, default=str, ensure_ascii=False)
    except Exception:
        s = str(obj)
    if len(s) > max_len:
        s = s[:max_len] + "..."
    return s
